### ISSUE TITLE
Update README to contain link to hosted game

### ISSUE THREAD

**Issue by addison-grant** [addison-grant/sweat-equity-2#22]
We should link to http://jasoniqbal.com/sweat-equity/index.html in the README.md if that's okay with you, @JasonIqbal

**Comment by JasonIqbal** [comment]
I am okay with it. Who owns the sweat-equity.xyz domain? I could set it to
point to my server.

**Comment by addison-grant** [comment]
I believe that would be @sterlinghirsh

**Comment by JasonIqbal** [comment]
Okay

**Comment by sterlinghirsh** [comment]
@addison-grant @JasonIqbal I would be happy to point the .xyz domain to your server, but I think it should be in the root directory. That is, I don't want to have to put sweat-equity.xyz/sweat-equity/ . Does that require a new server or hosting account or something?

**Comment by JasonIqbal** [comment]
I can set it up as a root directory. On friday evening or monday- tuesday
night I will get started on that project.

**Comment by JasonIqbal** [comment]
I started it. Where did you buy the domain from? I will need you to update
some things for it when I get to that part of the ordeal.

**Comment by sterlinghirsh** [comment]
I got it from namecheap. I'll be happy to update it when the time comes.

**Comment by JasonIqbal** [comment]
Thank you

**Comment by JasonIqbal** [comment]
Here is the endpoint for http://sweat-equity.xyz  and
http://www.sweat-equity.xyz

http://sweat-equity.xyz.s3-website-us-west-1.amazonaws.com

http://www.sweat-equity.xyz.s3-website-us-west-2.amazonaws.com

**Comment by JasonIqbal** [comment]
Here are the domain name servers

ns-933.awsdns-52.net.
ns-55.awsdns-06.com.
ns-1507.awsdns-60.org.
ns-1942.awsdns-50.co.uk.

**Comment by JasonIqbal** [comment]
send me a message when you update the web domain to these domain name
servers

**Comment by sterlinghirsh** [comment]
Hi there, sorry this took so long. I changed the dns settings in namecheap to point to that www url. It looks like this rn:
```
CNAME www www.sweat-equity.xyz.s3-website-us-west-2.amazonaws.com.
URL Redirect @ http://www.sweat-equity.xyz/
```
I appear to be unable to use the bare domain (http://sweat-equity.xyz) for anything other than redirecting to www if we're using CNAMEs, so that means we have to use www.sweat-equity.xyz. But the s3 versions seem to want to redirect us to http://sweat-equity.xyz without www. Is it possible to prevent redirecting like that on the s3 side?

**Comment by sterlinghirsh** [comment]
I tried putting the CNAME from www to the other non-www url, but it gave a 400 error.

**Comment by addison-grant** [comment]
@sterlinghirsh 
In a web browser:
- sweat-equity.xyz.s3-website-us-west-2.amazonaws.com is not working for me
- sweat-equity.xyz.s3-website-us-west-1.amazonaws.com is working for me

Maybe try making the CNAME line:
```
CNAME www sweat-equity.xyz.s3-website-us-west-1.amazonaws.com.
```

**Comment by sterlinghirsh** [comment]
I tried that but it didn't work either. When you go there with www in the title, it says it's in the wrong region.

**Comment by addison-grant** [comment]
I'm not sure what's wrong. @JasonIqbal, any ideas?

**Comment by JasonIqbal** [comment]
yes, I can change the redirect on my side.

**Comment by JasonIqbal** [comment]
it is caught in an infinite loop currently. I have the bare domain as the page and the www. as a redirect to the bare domain. I can change it if it helps.

**Comment by sterlinghirsh** [comment]
I need the www as the page and the bare domain redirect is handled on the dns side

**Comment by JasonIqbal** [comment]
Does it have the option to input your own DNS servers?

**Comment by JasonIqbal** [comment]
Did you use those amazon DNS server addresses I posted?

**Comment by sterlinghirsh** [comment]
Hm, it might. I didn't change the dns servers but I'm not sure that's relevant, unless there's something special going on I don't know.

**Comment by JasonIqbal** [comment]
Well if we tell cheap domains to use Amazon's dns servers instead of their
own servers then the request will arrive at Amazon's dns and it should
work. That is how I setup a Google domain I purchased using an s3. It
should be somewhere in the options which dns servers to use. For me, I had
to uncheck the 'use googles dns server' box.

**Comment by sterlinghirsh** [comment]
I tried this but it errored when I tried to put those nameservers you mentioned. I found a stackoverflow page on this, though: https://stackoverflow.com/questions/37555416/amazon-s3-static-hosting-with-namecheap-dns-how-to-correctly-route-non-www-pre

They suggest having the dns how I have it now, but have the bare domain redirect to www instead of vice-versa.

Otherwise I think there's a more complicated process for using Amazon's Route 53 dns maybe? I don't really understand that part.

**Comment by JasonIqbal** [comment]
Sure I'll switch it if it helps the setup for the domain and pushes our
team forward. I was hoping we would use Amazon's dns servers since they are
probably very close to Amazon's s3 servers and the delay would be reduced.
I wish I could look at your settings, as I imagine you would mine. It works
great for my website, but if the configuration options aren't available we
must make due.

**Comment by JasonIqbal** [comment]
Ya I had used route 53 for the setup to get those addresses.

**Comment by sterlinghirsh** [comment]
If you want to do a phone call or video chat, we can try to get it working. It's possible I did something wrong, but I copied and pasted exactly the nameservers you sent and it gave back a generic "something went wrong" error.

**Comment by JasonIqbal** [comment]
Okay I switched the buckets. All is good. I would have done it sooner, sorry I have been busy with my son.

**Comment by sterlinghirsh** [comment]
Cool it's working for me too

**Comment by JasonIqbal** [comment]
Thanks for working on the domain. I am glad, it feels like a real product.

If you want to work on some more projects, I am up for it. I have a few of
my own if anyone is interested.

**Comment by JasonIqbal** [comment]
Thank you

**Comment by addison-grant** [comment]
:+1:
